version: '3.8'

services:
  db:
    container_name: db
    image: rvitaly1978/hls:db
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    ports:
      - '${DB_PORT}:5432'
    networks:
      - hls

  app:
    container_name: app
    image: rvitaly1978/hls:app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_SECRET_REFRESH_KEY=${JWT_SECRET_REFRESH_KEY}
      - TOKEN_EXPIRE_TIME=${TOKEN_EXPIRE_TIME}
      - TOKEN_REFRESH_EXPIRE_TIME=${TOKEN_REFRESH_EXPIRE_TIME}
      - NODE_ENV=production
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    volumes:
      - app-logs:/app/logs
    networks:
      - hls

networks:
  hls:
    name: ${DB_NETWORK}
    driver: ${DB_DRIVER}

volumes:
  db-data:
  db-logs:
  app-logs:
